name: Branch Protection Check

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Check if PR is from fork
      run: |
        if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
          echo "PR is from a fork - additional checks may be required"
        else
          echo "PR is from the same repository"
        fi
    
    - name: Check author permissions
      run: |
        echo "PR Author: ${{ github.event.pull_request.user.login }}"
        echo "Repository Owner: ${{ github.repository_owner }}"
        
        if [ "${{ github.event.pull_request.user.login }}" != "${{ github.repository_owner }}" ]; then
          echo "⚠️ PR is from external contributor - review required"
        else
          echo "✅ PR is from repository owner"
        fi 